import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { ScrollArea } from "@/components/ui/scroll-area";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-dvh grid grid-cols-5")}>
        <ScrollArea className="border-r border-r-stone-200 max-h-dvh">
          <Sidebar />
        </ScrollArea>
        <ScrollArea className="col-span-4 bg-stone-50 h-full overflow-y-auto">
          <main className="py-8 px-10 h-[100rem]">{children}</main>
        </ScrollArea>
      </body>
    </html>
  );
}
